<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php echo $this->headMeta() ?>
	<title>ZettaCMS - Ошибка на сайте</title>
	<?php
		echo $this->headLink()
			->prependStylesheet($this->libUrl('/css/global.css'))
			->appendStylesheet($this->libUrl('/css/error.css'));
	?>
	
</head>

<body>

	<div id="body">

		<div class="logotype">
			<img src="<?php echo $this->libUrl('/i/logo.png')?>" class="logo" width="108" height="35" alt="ZettaCMS"/>
		</div>

		<!-- Begin layer -->
		<div class="layer color">

			<div class="content">
				<!-- Begin edit content -->

				<?php echo $this->layout()->content; ?>

				<!-- End edit content -->
			</div>
	
		</div>
		<!-- End layer -->

		<div class="empty"><!-- --></div>

		<div id="footer">
			<?php echo $this->partial('copyrights.phtml'); ?>
		</div>
	</div>
	<?php echo $this->headScript(); ?>
</body>
</html>