<!--googleoff: all-->
<!--noindex-->
	<noscript>
		<div class="overflow_all">
			<div id="msg_enable_js">Внимание! Для корректного отображения сайта необходимо включить javascript в вашем браузере.</div>
		</div>
	</noscript>
	
	<div id="ltie8_message">
		<div class="overflow_all">
			<div id="msg_update_browser">Внимание! Ваш браузер устарел. Для корректного отображения сайта необходимо <a href="http://windows.microsoft.com/ru-RU/internet-explorer/download-ie" target="_blank">обновить</a> бразуер до последней версии.</div>
		</div>
	</div>
<!--/noindex-->
<!--googleon: all-->