<?php echo $this->partial('admin/partialHead.phtml', array('subtitle' => !$this->key ? 'Добавление параметра' : 'Изменение параметра "' . $this->key . '"')); ?>
<div id="add_settings_form">
	<?php echo $this->form ?>
</div>
<div class="clear"><!-- --></div>
<a href="<?php echo $this->url(array('module' => 'Settings', 'controller' => 'admin'), 'mvc', true) ?>" id="z_back_url">&larr; <span>Отмена</span></a>