<?php echo $this->partial('admin/partialHead.phtml'); ?>

<?php if ($this->googleID): ?>
	<div id="visitors_3">Для просмотра статистики вам необходимо установить <a href="http://get.adobe.com/ru/flashplayer/" target="_blank">Adobe Flash Player</a>.</div>
	<div id="country"><!-- --></div>
	<div id="city"><!-- --></div>
<?php else : ?>
	Вы не указали "google_analytics_id" в <a href="<?php echo $this->url(array('module' => 'settings', 'controller' => 'admin'), 'mvc', true) ?>">настройках сайта</a>.
<?php endif ?>
	
<div class="z_buttons_placehoder"><!-- --></div>
	
<div class="clear"><!-- --></div>
<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'panel', 'action' => 'managepanel'), 'mvc', true) ?>" id="z_back_url">&larr; <span>Вернуться в управлениe</span></a>