<?php
	$full_url = $this->url(array('action'=>'add', 'key' => $this->key), 'mvc');
?>
<tr>
	<td><a href="<?php echo $full_url ?>"><?php echo $this->key ?></a></td>
	<td><?php echo $this->data['value'] ?></td>
	<td><?php echo $this->data['description'] ?></td>
	<td width="40">
		<div class="z_td_relative">
			<div class="z_icons">
				<a href="<?php echo $full_url ?>" class="z_ico_edit" title="Редактировать">Редактировать</a>
				<a href="<?php echo $this->url(array('action'=>'delete', 'key' => $this->key), 'mvc') ?>" class="z_ico_delete no_ajax" title="Удалить">Удалить</a>
			</div>
		</div>
	</td>
</tr>
