<script type="text/javascript">$.History.go('<?php echo $this->url(array('module' => 'publications', 'controller' => 'admin', 'action' => 'index'), 'mvc', true)?>');</script>

<?php echo $this->partial('admin/partialHead.phtml', array('subtitle' => 'Рубрика сохранена')); ?>
Данные сохранены. <a href="<?php echo $this->url(array('module' => 'publications', 'controller' => 'admin', 'action' => 'index'), 'mvc', true)?>">Перейти к списку рубрик</a>
<div class="clear"><!-- --></div>


