<script type="text/javascript">$.History.go('<?php echo $this->url(array('module' => 'publications', 'controller' => 'admin', 'action' => 'fields', 'rubric_id' => $this->rubric->rubric_id), 'mvc', true) ?>');</script>

<?php echo $this->partial('admin/partialHead.phtml', array('subtitle' => 'Поле сохранено')); ?>
Данные сохранены. <a href="<?php echo $this->url(array('module' => 'publications', 'controller' => 'admin', 'action' => 'fields', 'rubric_id' => $this->rubric->rubric_id), 'mvc', true) ?>">Перейти к списку полей</a>
<div class="clear"><!-- --></div>


