<?php
	$backUrl = $this->route_id
	? $this->url(array('module' => 'publications', 'controller' => 'admin', 'action' => 'view', 'rubric_id' => $this->rubric->rubric_id, 'route_id' => $this->route_id), 'mvc', true)
	: $this->url(array('module' => 'publications', 'controller' => 'admin', 'action' => 'routes', 'rubric_id' => $this->rubric->rubric_id), 'mvc', true);
?>

<?php echo $this->partial('admin/partialHead.phtml', array('subtitle' => 'Добавление публикации')); ?>

<div id="z_add_publication">
	<?php echo $this->form ?>
</div>

<div class="clear"><!-- --></div>
<a href="<?php echo $backUrl ?>" id="z_back_url">&larr; <span>Все публикации</span></a>
