<?php echo $this->partial('admin/partialHead.phtml', array('subtitle' => 'Публикации в модуле "' . $this->rubric->name . '" в маршруте "' . $this->route['name'] . '"')); ?>

<?php
    try {
        echo $this->partial('admin_' . $this->rubric->table_name . '/publications.phtml', $this);
    }
    catch (Exception $e) {
        echo $this->partial('admin/publications.phtml', $this);
    }
?>

<div class="z_buttons_placehoder">
	<a href="<?php echo $this->url(array('module' => 'publications', 'controller' => 'admin', 'action'=>'addpublication', 'rubric_id' => $this->rubric->rubric_id, 'route_id' => $this->route_id), 'mvc', true) ?>" class="ui-button">Добавить публикацию</a>
</div>


<div class="clear"><!-- --></div>
<a href="<?php echo $this->url(array('module' => 'publications', 'controller' => 'admin'), 'mvc', true) ?>" id="z_back_url">&larr; <span>Отмена</span></a>
