<?php

	$this->headLink()->exchangeArray(array());
	$this->headScript()->exchangeArray(array());
	
	echo $this->headLink()
		->appendStylesheet($this->libUrl('/Router/public/css/main.css'));
		
	echo $this->headScript()
		->appendScript('
			var _urlSaveTree = "' . $this->url(array('module' => 'Router', 'controller' => 'admin', 'action' => 'savetree'), 'mvc', true) . '";
			var _urlGetActions = "' . $this->url(array('module' => 'Router', 'controller' => 'admin', 'action' => 'getmoduleactions'), 'mvc', true) . '";
		')
		->appendFile($this->libUrl('/js/jquery/jquery.nestedSortable.js'))
		->appendFile($this->libUrl('/Router/public/js/main.js'));
		
?>

<div class="z_head_module">
	<img id="z_module_image" src="<? echo $this->libUrl('/Router/public/images/admin/ico.png')?>" alt="Управление деревом сайта"/>
	<div class="right">
		<h1>Структура сайта<?php echo ($this->subtitle ? ' &rarr; ' . $this->subtitle : '') ?></h1>
		<p>Управление деревом сайта</p>
	</div>
	<div class="clear"></div>
</div>