<?php

	$this->headLink()->exchangeArray(array());
	$this->headScript()->exchangeArray(array());

	echo $this->headLink()
		->appendStylesheet($this->libUrl('/Settings/public/css/admin.css'));

	echo $this->headScript()
		->appendFile($this->libUrl('/Settings/public/js/admin.js'));

?>

<div class="z_head_module">
	<img id="z_module_image" src="<?php echo $this->libUrl('/Settings/public/images/admin/ico.svg')?>" alt="Редактирование параметров сайта"/>
	<div class="right">
		<h1>Настройки<?php echo ($this->subtitle ? ' &rarr; ' . $this->subtitle : '') ?></h1>
		<p>Редактирование параметров сайта</p>
	</div>
	<div class="clear"></div>
</div>
