<?php

	$this->headLink()->exchangeArray(array());
	$this->headScript()->exchangeArray(array());

	echo $this->headLink()
		->appendStylesheet($this->libUrl('/Guitestcase/public/css/admin.css'));

?>

<div class="z_head_module">
	<img id="z_module_image" src="<?php echo  $this->libUrl('/Guitestcase/public/images/admin/ico.svg')?>" alt="Инструмент для тестирования кода"/>
	<div class="right">
		<h1>Тестер<?php echo ($this->subtitle ? ' &rarr; ' . $this->subtitle : '') ?></h1>
		<p>Инструмент для тестирования кода</p>
	</div>
	<div class="clear"></div>
</div>
