<script type="text/javascript">$.History.go('<?php echo $this->url(array('action' => 'index'), 'mvc')?>');</script>

<?php echo $this->partial('admin/partialHead.phtml', array('subtitle' => $this->translate('Saved'))); ?>
<?php echo $this->translate('Data saved') ?>. <a href="<?php echo $this->url(array('action' => 'index'), 'mvc')?>"><?php echo $this->translate('View saved data') ?>.</a>
<div class="clear"><!-- --></div>


