<?php

	$this->headLink()->exchangeArray(array());
	$this->headScript()->exchangeArray(array());

	echo $this->headLink()
		->appendStylesheet($this->libUrl('/Seo/public/css/admin.css'));

	echo $this->headScript()
		->appendFile($this->libUrl('/js/jquery/jquery.defaultValue.js'))
		->appendFile($this->libUrl('/Seo/public/js/admin.js'));

?>

<div class="z_head_module">
	<img id="z_module_image" src="<?php echo $this->libUrl('/Seo/public/images/admin/ico.png')?>" alt="<?php echo $this->translate('Search Engine Optimization')?>"/>
	<div class="right">
		<h1>SEO<?php echo ($this->subtitle ? ' &rarr; ' . $this->subtitle : '') ?></h1>
		<p><?php echo $this->translate('Search Engine Optimization') ?></p>
	</div>
	<div class="clear"></div>
</div>