<?php

	if (Zetta_Acl::getInstance()->has('route_' . $this->item_id) && !Zetta_Acl::getInstance()->isAllowed('route_' . $this->item_id)) {
		$this->disable = true;
	}

	if (!$this->disable) {

?>

		<li data-id="<?php echo $this->item_id ?>" class="item_<?php echo $this->partialCounter ?> id_<?php echo $this->item_id ?> <?php echo ($this->current ? 'active' : '') ?>">
			<a href="<?php echo (!$this->external_link ? $this->baseUrl() : '') . $this->url ?>"><?php echo $this->name ?></a>

			<?php 
				if (sizeof($this->childs)) {
					$childTree = $this->partialLoop('menu/partialItem.phtml', $this->childs);
					echo $childTree ? '<ul>' . $childTree . '</ul>' : '';
				}
			?>

		</li>

<?php } ?>
