<script type="text/javascript">$.History.go('<?php echo $this->url(array('module' => 'access', 'controller' => 'admin', 'action' => 'roles'), 'mvc', true) ?>');</script>

<?php echo $this->partial('admin/partialHead.phtml', array('subtitle' => 'Данные сохранёны')); ?>
Данные сохранены. <a href="<?php echo $this->url(array('module' => 'access', 'controller' => 'admin', 'action' => 'roles'), 'mvc', true) ?>">Перейти к списку ролей</a>
<div class="clear"><!-- --></div>


