<?php echo $this->partial('admin/partialHead.phtml', array('subtitle' => 'Доступные привилегии')); ?>


<?php
	if (sizeof($this->resources)) {
		?><ul><?php
		echo $this->partialLoop('admin/partialResourcesList.phtml', $this->resources);
		?></ul><?php
	}
	else {
		echo 'Не создано ни одной привилегии.';
	}
?>


<div class="z_buttons_placehoder">
	<a href="<?php echo $this->url(array('module' => 'access', 'controller' => 'admin', 'action'=>'add'), 'mvc', true) ?>" class="ui-button">Добавить привилегию</a>
	<a href="<?php echo $this->url(array('module' => 'access', 'controller' => 'admin', 'action'=>'roles'), 'mvc', true) ?>" class="ui-button">Управление ролями</a>
</div>

<div class="clear"><!-- --></div>
<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'panel', 'action' => 'managepanel'), 'mvc', true) ?>" id="z_back_url">&larr; <span>Вернуться в управлениe</span></a>
