<script type="text/javascript">$.History.go('<?php echo $this->url(array('action' => 'users', 'role_id' => ($this->role ? $this->role->name : false)), 'mvc')?>');</script>

<?php echo $this->partial('admin/partialHead.phtml', array('subtitle' => 'Данные сохранёны')); ?>
Данные сохранены. <a href="<?php echo $this->url(array('action' => 'users', 'role_id' => ($this->role ? $this->role->name : false)), 'mvc')?>">Перейти к списку пользователей</a>
<div class="clear"><!-- --></div>


