<?php

	$this->headLink()->exchangeArray(array());
	$this->headScript()->exchangeArray(array());
	
	echo $this->headLink()
		->appendStylesheet($this->libUrl('/Accessusers/public/css/admin.css'));
		
	echo $this->headScript()
		->appendFile($this->libUrl('/Accessusers/public/js/admin.js'));
		
?>

<div class="z_head_module">
	<img id="z_module_image" src="<? echo $this->libUrl('/Accessusers/public/images/admin/ico.png')?>" alt="Управление сообществом сайта"/>
	<div class="right">
		<h1>Пользователи<?php echo ($this->subtitle ? ' &rarr; ' . $this->subtitle : '') ?></h1>
		<p>Управление сообществом сайта</p>
	</div>
	<div class="clear"></div>
</div>