<script type="text/javascript">$.History.go('<?php echo $this->url(array('module' => 'menu', 'controller' => 'admin', 'action' => 'tree', 'menu_id' => $this->menu_id), 'mvc', true) ?>');</script>

<?php echo $this->partial('admin/partialHead.phtml', array('subtitle' => 'Раздел сохранён')); ?>
Данные сохранены. <a href="<?php echo $this->url(array('module' => 'menu', 'controller' => 'admin', 'action' => 'tree', 'menu_id' => $this->menu_id), 'mvc', true) ?>">Перейти к списку разделов меню</a>
<div class="clear"><!-- --></div>


