<?php echo $this->partial('admin/partialHead.phtml', array('subtitle' => $this->item_id ? 'Свойства раздела' : 'Добавление раздела')); ?>
<div id="add_route_form">
	<?php echo $this->form ?>
</div>
<div class="clear"><!-- --></div>
<a href="<?php echo $this->url(array('module' => 'menu', 'controller' => 'admin', 'action' => 'tree', 'menu_id' => $this->menu_id), 'mvc', true) ?>" id="z_back_url">&larr; <span>Отмена</span></a>