<aside class="z_admin_wrapper z_admin_block <?php
	if ($this->inherit) {
		echo ($this->block && $this->route_current_id != 1 && $this->route_current_id == $this->block->route_id ? 'z_override_block' : '');
		echo (!$this->block || $this->route_current_id != 1 && $this->route_current_id != $this->block->route_id ? 'z_inherit_block' : '');
	}
?>" data-block-name="<?php echo $this->block_name ?>" data-block-type="<?php echo $this->block_type ?>">

	<div class="z_redactor"><?php echo $this->content ?></div>

	<aside class="z_icons_editable">
		<var class="icon-pencil no_ajax" title="Редактировать"></var>
		<var href="#" class="icon-lock no_ajax" title="Убрать наследование с главной страницы"></var>
		<var href="#" class="icon-unlock no_ajax" title="Наследовать с главной страницы"></var>
	</aside>

</aside>
